import {
  Calendar,
  FileText,
  Clock,
  Hash,
  User,
  BarChart3,
  Target,
  Users,
  MessageCircle,
  Paperclip,
  Timer,
  GitBranch,
  Layers,
} from "lucide-react";

export const AVAILABLE_COLUMN_TYPES = [
  {
    id: "description",
    label: "Mô tả",
    type: "text" as const,
    icon: FileText,
    description: "Mô tả công việc",
  },
  {
    id: "taskNumber",
    label: "Mã công việc",
    type: "number" as const,
    icon: Hash,
    description: "Số hoặc ID công việc",
  },
  {
    id: "timeline",
    label: "Dòng thời gian",
    type: "dateRange" as const,
    icon: Calendar,
    description: "Ngày bắt đầu và hạn hoàn thành",
  },
  {
    id: "completedAt",
    label: "Ngày hoàn thành",
    type: "date" as const,
    icon: Calendar,
    description: "Ngày hoàn thành công việc",
  },
  {
    id: "storyPoints",
    label: "Điểm ước lượng",
    type: "number" as const,
    icon: Target,
    description: "Ước lượng điểm công việc",
  },
  {
    id: "originalEstimate",
    label: "Ước lượng ban đầu",
    type: "number" as const,
    icon: Clock,
    description: "Ước lượng thời gian ban đầu",
  },
  {
    id: "remainingEstimate",
    label: "Thời gian còn lại",
    type: "number" as const,
    icon: BarChart3,
    description: "Ước lượng thời gian còn lại",
  },

  {
    id: "createdAt",
    label: "Ngày tạo",
    type: "date" as const,
    icon: Calendar,
    description: "Ngày tạo công việc",
  },
  {
    id: "updatedAt",
    label: "Ngày cập nhật",
    type: "date" as const,
    icon: Calendar,
    description: "Ngày cập nhật gần nhất",
  },

  {
    id: "parentTask",
    label: "Công việc cha",
    type: "text" as const,
    icon: Layers,
    description: "Tham chiếu công việc cha",
  },
  {
    id: "childTasksCount",
    label: "Công việc con",
    type: "number" as const,
    icon: Layers,
    description: "Số công việc con",
  },
  {
    id: "commentsCount",
    label: "Bình luận",
    type: "number" as const,
    icon: MessageCircle,
    description: "Số bình luận",
  },
  {
    id: "attachmentsCount",
    label: "Tệp đính kèm",
    type: "number" as const,
    icon: Paperclip,
    description: "Số tệp đính kèm",
  },
  {
    id: "progressPercent",
    label: "Tiến độ",
    type: "number" as const,
    icon: Timer,
    description: "Tiến độ công việc (%)",
  },
];
